dataset:
  path: "titanic.csv"
  target: "Survived"

train:
  random_state: 42
  test_size: 0.2
  model:
    type: "RandomForest"
    n_estimators: 100
    max_depth: 8

mlflow:
  experiment_name: "titanic-mlops"
  tracking_uri: "file:./mlruns"

output:
  model_name: "rf_titanic_model"
