name: ML Pipeline CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-train:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3️⃣ Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install

    # 4️⃣ Ejecutar pruebas (si las tienes)
    - name: Run tests
      run: |
        make test || echo "No tests yet"

    # 5️⃣ Entrenar el modelo
    - name: Train model
      run: |
        make train

    # 6️⃣ Subir el modelo como artefacto
    - name: Upload trained model
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: mlruns/
